name: Dream Big
favicon: null
layout_spectrum: 0.0524229621514678
typography_spectrum: 0.8894025401677936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8204983919858932
  lightness: 0.16417959542013705
  saturation: 0.09461871162056923
  rhythmicContrast: 0.7536655894946307
purpose: []
